const HomeFeeds = [
  {
    id: 1,
    userid: 1,
    name: "Lana White",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 3,
    userid: 3,
    name: "Dodo Vincey",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 4,
    userid: 4,
    name: "Emaly Shea",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 5,
    userid: 5,
    name: "Fatema Anny",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 6,
    userid: 6,
    name: "Evrahim Alli",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 7,
    userid: 7,
    name: "Mohammed Nabi",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 8,
    userid: 8,
    name: "Ema Cliopetra",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 10,
    userid: 10,
    name: "Muskan Khan",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 11,
    userid: 11,
    name: "Nuva Akhi",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 12,
    userid: 12,
    name: "David Milar",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
  {
    id: 13,
    userid: 13,
    name: "Malkova Williams",
    feedImage: "",
    feedProfile: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, distinctio",
  },
];

export default HomeFeeds;
